site_name: Caderno Aberto
site_url: https://ciencialine.github.io/caderno-aberto/
repo_name: ciencialine/caderno-aberto
repo_url: https://github.com/ciencialine/caderno-aberto
nav:
  - Home: index.md
  - 6o ano:
      - Ciências:
          - 6/ciencias/ciclo-das-rochas-e-eras-geologicas.md
          - 6/ciencias/estrutura-interna-da-terra.md
          - 6/ciencias/hidrosfera.md
          - 6/ciencias/solo:-formacao,-tipos,-degradacao-e-conservacao.md
  - 9o ano:
      - Ciências:
          - 9/ciencias/divisao-celular.md
          - 9/ciencias/elemento-e-substancia-quimica.md
          - 9/ciencias/estados-fisicos-da-materia.md
          - 9/ciencias/evolucao-dos-modelos-atomicos.md
          - 9/ciencias/leis-ponderais-e-reacoes-quimicas.md
          - 9/ciencias/ligacoes-quimicas-e-geometria-molecular.md
          - 9/ciencias/transformacoes-fisicas-e-quimicas.md
  - Contribuindo: contribuindo.md
  - Manifesto: manifesto.md
  - Sobre: sobre.md
theme:
  name: material
  features:
    - search.share
