site_name: Cderno Aberto
site_url: https://ciencialine.github.io/caderno-aberto/
repo_name: ciencialine/caderno-aberto
repo_url: https://github.com/ciencialine/caderno-aberto
nav:
  - Home: index.md
  - 6o ano:
    - Ciências:
      - Camadas internas da terra: 6/ciencias/camadas-internas-da-terra.md
      - Hidrosfera: 6/ciencias/hidrosfera.md
  - 9o ano:
    - Ciências:
      - Evolução dos modelos atômicos: 9/ciencias/evolucao-dos-modelos-atomicos.md
      - Elemento e substância química: 9/ciencias/elemento-e-substancia-quimica.md
      - Estados físicos da matéria: 9/ciencias/estados-fisicos-da-materia.md
  - Contribuindo: contribuindo.md
  - Manifesto: manifesto.md
  - Sobre: sobre.md
theme:
  name: material
  features:
    - search.share
